# Generated by Django 3.1.7 on 2021-05-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('explanation', models.CharField(blank=True, max_length=10000)),
                ('url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
